export const LOCAL = {
    COMMON_PREFIXES: {
        SEND: 'Отправить',
        ADD: 'Добавить',
        SAVE: 'Сохранить',
        REPLY: 'Ответить',
    },
    PAGES: {
        HOME: 'Главная',
        SIGNIN: 'Вход',
        SIGNUP: 'Регистрация',
        PROFILE: 'Профиль',
        PROFILE_PASSWORD: 'Изменение пароля',
        PROFILE_DATA: 'Изменение данных',
        FORUM: 'Форум',
        TOPIC: 'Форум: тема',
        GAME: 'Игра',
        GAME_START: 'Начать игру',
        LEADERBOARD: 'Таблица лидеров',
        SETTINGS: 'Настройки',
    },
    AUTHORIZE: 'Авторизоваться',
    AUTHORIZE_YANDEX: 'Войти через Яндекс',
    REGISTER: 'Зарегистрироваться',
    NO_ACCOUNT: 'Нет пароля?',
    CHANGE_PROFILE_DATA: 'Изменить данные',
    CHANGE_PROFILE_PASSWORD: 'Изменить пароль',
    BACK: 'Назад',
    AVATAR_DEFAULT: 'LP',
    RECORD: 'Рекорд',
    EXIT: 'Выйти',
    FORUM_COLUMN_TOPIC: 'Тема',
    FORUM_COLUMN_COMMENT: 'Комментарий',
    FORUM_COLUMN_COMMENT_EMPTY: 'Комментарии отсутствуют...',
    FORUM_COLUMN_REVIEWS: 'Просмотры',
    FORUM_COLUMN_ANSWERS: 'Ответы',
    FORUM_COLUMN_AUTOR: 'Автор',
    DATE_UPDATE: 'Дата обновление',
    DATE_CREATE: 'Дата создания',
    LEADERBOARD_COLUMN_PLAYER: 'Игрок',
    LEADERBOARD_COLUMN_SCORE: 'Счет',
    GAME_NAME: 'Last Practicant',
    GAME_START: 'Начать игру',
    GAME_NEXT_LEVEL: 'Следующий уровень',
    GAME_LEVEL_COMPLITE: 'Уровень завершен!',
    GAME_OVER: 'Игра закончена',
    GAME_RESET: 'Заново?',
    GAME_CONTROL: 'Управление',
    GAME_SCORE: 'Счет',
    GAME_CONTROL_JUMP: 'Прыгнуть - стрелка вверх',
    GAME_CONTROL_DOWN: 'Присесть - стрелка вниз',
    GAME_CONTROL_SHOTE: 'Выстрел - пробел',
    GAME_CONTROL_FULLSCREEN: 'На весь экран - двойной клик по области',
    ERROR_PAGE_DESC: 'Вы можете перейти на',
    ERROR_PAGE_LINK: 'Главную',
    ERROR_SIGNIN: 'Не удалось авторизоваться, проверьте правильность введенных данных',
    SETTINGS_THEME: 'Светлая тема',
    MUSIC: 'Музыка',
};
