export const LOCAL = {
    AUTHORIZE: 'Войти',
    REGISTER: 'Зарегистрироваться',
    CHANGE_PROFILE_DATA: 'Изменить данные',
    CHANGE_PROFILE_PASSWORD: 'Изменить пароль',
    SAVE: 'Сохранить',
    BACK: 'Назад',
    AVATAR_DEFAULT: 'LP',
    RECORD: 'Рекорд',
    EXIT: 'Выйти',
    FORUM_COLUMN_TOPIC: 'Тема',
    FORUM_COLUMN_REVIEWS: 'Просмотры',
    FORUM_COLUMN_ANSWERS: 'Ответы',
    FORUM_COLUMN_AUTOR: 'Автор',
    LEADERBOARD_COLUMN_PLAYER: 'Игрок',
    LEADERBOARD_COLUMN_SCORE: 'Счет',
    GAME_START: 'Начать игру',
    GAME_NEXT_LEVEL: 'Следующий уровень',
    GAME_LEVEL_COMPLITE: 'Уровень завершен!',
    GAME_OVER: 'Игра закончена',
    GAME_RESET: 'Заново?',
    GAME_CONTROL: 'Управление',
    GAME_SCORE: 'Счет',
    GAME_CONTROL_JUMP: 'Прыгнуть - стрелка вверх',
    GAME_CONTROL_DOWN: 'Присесть - стрелка вниз',
    GAME_CONTROL_SHOTE: 'Выстрел - пробел',
};
